FROM ubuntu:16.04

RUN apt-get -y update -qq
RUN apt-get -y upgrade
RUN apt-get install -y build-essential software-properties-common python-software-properties curl ruby ruby-dev autoconf libffi-dev
RUN apt-get -y update -qq
RUN apt-get -y autoremove
RUN gem install fpm-cookery